const KEY='fitnessV3';
const defaults={settings:{startWeight:84.3,goalWeight:70,weeklyRun:37,waterGoal:4},logs:{}};
let state=JSON.parse(localStorage.getItem(KEY)||localStorage.getItem('fitnessV2')||JSON.stringify(defaults));
if(!state.settings)state.settings=structuredClone(defaults.settings);if(!state.logs)state.logs={};
const schedule={Monday:{workout:'Chest + Triceps',run:5,hiit:6},Tuesday:{workout:'Back + Biceps',run:0,hiit:6,special:true},Wednesday:{workout:'Shoulders + Abs/Core',run:0,hiit:3,special:true},Thursday:{workout:'Legs + Calves',run:4,hiit:6},Friday:{workout:'Chest + Back',run:8,hiit:3},Saturday:{workout:'Arms + Abs',run:10,hiit:3},Sunday:{workout:'Rest from lifting',run:10,hiit:3},Other:{workout:'Custom / Recovery',run:0,hiit:0,other:true}};
const $=id=>document.getElementById(id),iso=(d=new Date())=>{const z=new Date(d.getTime()-d.getTimezoneOffset()*60000);return z.toISOString().slice(0,10)},weekday=date=>new Date(date+'T12:00:00').toLocaleDateString('en-CA',{weekday:'long'}),logs=()=>Object.values(state.logs).sort((a,b)=>a.date.localeCompare(b.date));let calendarDate=new Date();
function requirements(date){const d=weekday(date),s=schedule[d]||schedule.Other;return{workout:!s.other&&d!=='Sunday',kriya:true,hiit:!s.other,run:s.run>0,water:true,sleep:true}}
function score(log){if(!log)return 0;const r=requirements(log.date),checks=[log.kriya,Number(log.water)>=state.settings.waterGoal,Number(log.sleep)>=7];if(r.workout)checks.push(log.strength);if(r.hiit)checks.push(log.hiit);if(r.run)checks.push(Number(log.km)>0);return Math.round(checks.filter(Boolean).length/checks.length*100)}
function saveLocal(){localStorage.setItem(KEY,JSON.stringify(state));$('sync').textContent='Saving...';window.cloudSave?.(state)}
function showPage(id){document.querySelectorAll('.page,.tab,.bottom-nav button').forEach(x=>x.classList.remove('active'));$(id).classList.add('active');document.querySelectorAll(`[data-page="${id}"]`).forEach(x=>x.classList.add('active'));renderAll()}
document.querySelectorAll('[data-page]').forEach(x=>x.onclick=()=>showPage(x.dataset.page));
function buildPlan(day,type){const s=schedule[day],part=type==='Part-time',a=[];if(s.special){a.push(['5:00 AM - 5:45 AM','Morning Workout: '+s.workout,'Start the day with the workout']);a.push(['6:00 AM - 7:30 AM','Kriya + Meditation','Complete after the workout'])}else{a.push(['6:00 AM - 7:30 AM','Kriya + Meditation','Daily practice']);if(!s.other&&day!=='Sunday')a.push(['7:40 AM - 8:25 AM','Morning Workout: '+s.workout,'Strength and flexibility'])}a.push(['9:00 AM - 5:00 PM','Work','']);if(part)a.push(['5:45 PM - 10:15 PM','Part-Time Job','Eat dinner during the shift']);if(s.run)a.push([part?'After work':'Evening','Evening Run: '+s.run+' km','Evening running only']);if(s.hiit)a.push([part?'After returning home':s.run?'After run':'Evening','Evening HIIT: '+s.hiit+' rounds','Circuit'+(s.special?'|mandatory':'')]);if(part)a.push(['Immediately after HIIT','Freshen Up + Sleep','Dinner already completed during the shift']);return a}
function timeline(id,a){$(id).innerHTML=a.map(x=>`<div class="event"><div class="event-time">${x[0]}</div><div><div class="event-title">${x[1]}${x[2].includes('|mandatory')?'<span class="tag">MANDATORY</span>':''}</div><div class="event-detail">${x[2].replace('|mandatory','')}</div></div></div>`).join('')}
function formData(){return{date:$('fDate').value,type:$('fType').value,kriya:$('fKriya').checked,strength:$('fStrength').checked,hiit:$('fHiit').checked,rounds:+$('fRounds').value,km:+$('fKm').value,runMinutes:+$('fRunMinutes').value,water:+$('fWater').value,sleep:+$('fSleep').value,weight:$('fWeight').value?+$('fWeight').value:null,energy:+$('fEnergy').value,notes:$('fNotes').value}}
function renderRequirements(){const r=requirements($('fDate').value),labels=[];if(r.workout)labels.push('Workout');labels.push('Kriya');if(r.hiit)labels.push('HIIT');if(r.run)labels.push('Run');labels.push('Water','Sleep');$('dayRequirements').innerHTML='<b>Required today</b><p class="muted">'+labels.join(' • ')+'</p>';$('fKm').disabled=!r.run;$('fRunMinutes').disabled=!r.run}
$('checkForm').oninput=()=>{$('liveScore').textContent=score(formData())+'%';renderRequirements()};
$('checkForm').onsubmit=async e=>{e.preventDefault();$('saveBtn').disabled=true;const l=formData();state.logs[l.date]=l;saveLocal();renderAll();$('saveBtn').disabled=false;alert('Check-in saved and synchronized.')};
function loadEntry(date=$('fDate').value){const l=state.logs[date];$('fDate').value=date;if(!l){['fKriya','fStrength','fHiit'].forEach(x=>$(x).checked=false);['fRounds','fKm','fRunMinutes','fWater','fSleep'].forEach(x=>$(x).value=0);$('fWeight').value='';$('fNotes').value='';renderRequirements();$('liveScore').textContent='0%';return}const map={fType:'type',fRounds:'rounds',fKm:'km',fRunMinutes:'runMinutes',fWater:'water',fSleep:'sleep',fWeight:'weight',fEnergy:'energy',fNotes:'notes'};Object.entries(map).forEach(([id,k])=>$(id).value=l[k]??'');$('fKriya').checked=!!l.kriya;$('fStrength').checked=!!l.strength;$('fHiit').checked=!!l.hiit;$('liveScore').textContent=score(l)+'%';renderRequirements()}
function consecutive(predicate,onlyScheduled=false){let n=0,d=new Date();for(let i=0;i<730;i++){const key=iso(d),day=weekday(key),req=requirements(key);if(onlyScheduled&&!req.run){d.setDate(d.getDate()-1);continue}const l=state.logs[key];if(!l||!predicate(l,req,day))break;n++;d.setDate(d.getDate()-1)}return n}
function renderStreaks(){const cards=[['Check-In',consecutive(()=>true)],['Workout',consecutive((l,r)=>!r.workout||l.strength)],['Kriya',consecutive(l=>l.kriya)],['HIIT',consecutive((l,r)=>!r.hiit||l.hiit)],['Water',consecutive(l=>+l.water>=state.settings.waterGoal)],['Sleep',consecutive(l=>+l.sleep>=7)],['Scheduled Run',consecutive(l=>+l.km>0,true)]];$('streakCards').innerHTML=cards.map(x=>`<div class="streak"><span class="label">${x[0]}</span><b>${x[1]} days</b></div>`).join('')}
function weightSeries(){return logs().filter(x=>+x.weight>0).map(x=>({date:x.date,value:+x.weight}))}
function drawChart(id){const c=$(id),ctx=c.getContext('2d'),a=weightSeries();ctx.clearRect(0,0,c.width,c.height);ctx.strokeStyle='#e5eaf2';ctx.lineWidth=1;for(let i=0;i<5;i++){ctx.beginPath();ctx.moveTo(42,20+i*48);ctx.lineTo(c.width-15,20+i*48);ctx.stroke()}if(!a.length){ctx.fillStyle='#71809d';ctx.font='14px Segoe UI';ctx.fillText('Add weight in Daily Check-In to build the trend.',52,130);return}const vals=a.map(x=>x.value),min=Math.min(...vals,state.settings.goalWeight)-1,max=Math.max(...vals,state.settings.startWeight)+1;ctx.strokeStyle='#4e6fff';ctx.lineWidth=3;ctx.beginPath();a.forEach((x,i)=>{const px=42+(c.width-65)*(i/Math.max(1,a.length-1)),py=20+192*(max-x.value)/(max-min);i?ctx.lineTo(px,py):ctx.moveTo(px,py)});ctx.stroke();ctx.fillStyle='#4e6fff';a.forEach((x,i)=>{const px=42+(c.width-65)*(i/Math.max(1,a.length-1)),py=20+192*(max-x.value)/(max-min);ctx.beginPath();ctx.arc(px,py,4,0,Math.PI*2);ctx.fill()})}
function renderDashboard(){const a=logs(),ws=weightSeries(),cw=ws.length?ws.at(-1).value:state.settings.startWeight,lost=Math.max(0,state.settings.startWeight-cw),remaining=Math.max(0,cw-state.settings.goalWeight);$('kWeight').textContent=cw.toFixed(1)+' kg';$('kWeightSub').textContent=lost.toFixed(1)+' kg lost • '+remaining.toFixed(1)+' kg remaining';$('kStreak').textContent=consecutive(()=>true)+' days';const now=new Date(),monday=new Date(now);monday.setDate(now.getDate()-((now.getDay()+6)%7));monday.setHours(0,0,0,0);const wk=a.filter(x=>new Date(x.date+'T12:00')>=monday).reduce((n,x)=>n+(+x.km||0),0);$('kRun').textContent=wk.toFixed(1)+' km';$('kRunSub').textContent='Target: '+state.settings.weeklyRun+' km';$('kScore').textContent=score(state.logs[iso()])+'%';$('todayText').textContent=new Date().toLocaleDateString('en-CA',{weekday:'long',month:'long',day:'numeric',year:'numeric'});timeline('todayPlan',buildPlan(weekday(iso()),state.logs[iso()]?.type||'Regular'));renderStreaks();drawChart('weightChart')}
function renderCalendar(){const y=calendarDate.getFullYear(),m=calendarDate.getMonth();$('calendarTitle').textContent=new Date(y,m,1).toLocaleDateString('en-CA',{month:'long',year:'numeric'});const first=(new Date(y,m,1).getDay()+6)%7,days=new Date(y,m+1,0).getDate();let html=['Mon','Tue','Wed','Thu','Fri','Sat','Sun'].map(x=>`<div class="dow">${x}</div>`).join('');for(let i=0;i<first;i++)html+='<div class="day empty"></div>';for(let d=1;d<=days;d++){const key=iso(new Date(y,m,d)),l=state.logs[key],s=l?score(l):null,cls=s===100?'perfect':s>=60?'partial':l?'low':'',today=key===iso()?' today':'';html+=`<div class="day ${cls}${today}" onclick="selectCalendarDay('${key}')"><b>${d}</b>${l?`<small>${s}%</small>`:''}</div>`}$('calendarGrid').innerHTML=html}
function moveMonth(n){calendarDate.setMonth(calendarDate.getMonth()+n);renderCalendar()}
function selectCalendarDay(key){const l=state.logs[key];$('selectedDay').innerHTML=`<b>${new Date(key+'T12:00').toLocaleDateString('en-CA',{weekday:'long',month:'long',day:'numeric'})}</b><p>${l?'Score: '+score(l)+'%<br>Run: '+(+l.km||0)+' km<br>Water: '+(+l.water||0)+' L<br>Sleep: '+(+l.sleep||0)+' h':'No entry saved.'}</p><button class="btn primary" onclick="editCalendarDay('${key}')">${l?'Edit entry':'Add entry'}</button>`}
function editCalendarDay(key){showPage('checkin');loadEntry(key)}
function renderAnalytics(){const now=new Date(),month=now.getMonth(),year=now.getFullYear(),runs=logs().filter(x=>+x.km>0),monthRuns=runs.filter(x=>{const d=new Date(x.date+'T12:00');return d.getMonth()===month&&d.getFullYear()===year});const vals=runs.map(x=>+x.km);$('aMonthRun').textContent=monthRuns.reduce((a,x)=>a+(+x.km||0),0).toFixed(1)+' km';$('aLongest').textContent=(vals.length?Math.max(...vals):0).toFixed(1)+' km';$('aAverage').textContent=(vals.length?vals.reduce((a,b)=>a+b,0)/vals.length:0).toFixed(1)+' km';$('aRuns').textContent=vals.length;const names=['Mon','Tue','Wed','Thu','Fri','Sat','Sun'],tot=Array(7).fill(0);runs.forEach(x=>{const d=(new Date(x.date+'T12:00').getDay()+6)%7;tot[d]+=+x.km});const mx=Math.max(...tot,1);$('runBars').innerHTML=names.map((n,i)=>`<div class="barrow"><b>${n}</b><div class="bar"><i style="width:${tot[i]/mx*100}%"></i></div><span>${tot[i].toFixed(1)} km</span></div>`).join('');drawChart('analyticsChart')}
function renderRoutine(){const d=$('rDay').value||weekday(iso()),s=schedule[d];$('routineSummary').innerHTML=`<b>${d}</b><br>Workout: ${s.workout}<br>Run: ${s.run?s.run+' km, evening only':'No run'}<br>HIIT: ${s.hiit?s.hiit+' rounds'+(s.special?' mandatory':''):'Custom'}`;timeline('routinePlan',buildPlan(d,$('rType').value))}
function renderHistory(){$('historyRows').innerHTML=logs().slice().reverse().map(l=>`<tr><td>${l.date}</td><td><b>${score(l)}%</b></td><td>${l.strength?'Yes':'No'}</td><td>${l.kriya?'Yes':'No'}</td><td>${l.hiit?'Yes':'No'}</td><td>${+l.km||0} km</td><td>${+l.water||0} L</td><td>${+l.sleep||0} h</td><td>${l.weight||'-'}</td><td><button class="btn danger" onclick="deleteEntry('${l.date}')">Delete</button></td></tr>`).join('')||'<tr><td colspan="10">No entries yet.</td></tr>'}
function deleteEntry(k){if(confirm('Delete this entry?')){delete state.logs[k];saveLocal();renderAll()}}
$('settingsForm').onsubmit=e=>{e.preventDefault();state.settings={startWeight:+$('sStart').value,goalWeight:+$('sGoal').value,weeklyRun:+$('sRun').value,waterGoal:+$('sWater').value};saveLocal();renderAll()};
function exportCsv(){const h=['date','score','workout','kriya','hiit','km','runMinutes','water','sleep','weight','energy','notes'],a=[h.join(',')];logs().forEach(l=>a.push(h.map(k=>JSON.stringify(k==='score'?score(l):l[k]??'')).join(',')));const x=document.createElement('a');x.href=URL.createObjectURL(new Blob([a.join('\n')],{type:'text/csv'}));x.download='fitness-v3-history.csv';x.click()}
function renderAll(){renderDashboard();renderCalendar();renderAnalytics();renderRoutine();renderHistory();renderRequirements();$('liveScore').textContent=score(formData())+'%'}
function init(){$('fDate').value=iso();$('rDay').innerHTML=Object.keys(schedule).map(x=>`<option>${x}</option>`).join('');$('rDay').value=weekday(iso());$('rDay').onchange=$('rType').onchange=renderRoutine;const s=state.settings;$('sStart').value=s.startWeight;$('sGoal').value=s.goalWeight;$('sRun').value=s.weeklyRun;$('sWater').value=s.waterGoal;renderAll()}
init();
(function authInit(){const message=e=>$('authError').textContent=e?.message||String(e);if(!window.firebaseConfig){message('firebase-config.js is missing.');return}firebase.initializeApp(firebaseConfig);const auth=firebase.auth(),db=firebase.firestore();window.cloudSave=async data=>{if(!auth.currentUser)return;try{await db.collection('users').doc(auth.currentUser.uid).set(data);$('sync').textContent='Cloud synced'}catch(e){$('sync').textContent='Sync failed';message(e)}};auth.onAuthStateChanged(async user=>{if(!user){$('auth').classList.remove('hidden');return}$('auth').classList.add('hidden');$('account').textContent=user.email;try{const snap=await db.collection('users').doc(user.uid).get();if(snap.exists){const cloud=snap.data();state={settings:{...defaults.settings,...cloud.settings},logs:cloud.logs||{}};localStorage.setItem(KEY,JSON.stringify(state));init()}else await window.cloudSave(state)}catch(e){message(e)}});$('login').onclick=()=>auth.signInWithEmailAndPassword($('email').value,$('password').value).catch(message);$('signup').onclick=()=>auth.createUserWithEmailAndPassword($('email').value,$('password').value).catch(message);$('logout').onclick=()=>auth.signOut();$('forgot').onclick=()=>{if(!$('email').value)return message('Enter your email first.');auth.sendPasswordResetEmail($('email').value).then(()=>message('Password reset email sent.')).catch(message)}})();
